// Rasterize the AbleJam grid logo (the 3x3 clip matrix with the orange centre) into the
// app icons electron-builder + the BrowserWindow use. Run once (or when the logo changes):
//   node make-icon.mjs   ->   build/icon.png (1024, master) + build/icon.ico (multi-size)
// .icns for macOS is generated by electron-builder from build/icon.png at mac-build time.
import sharp from "sharp";
import pngToIco from "png-to-ico";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const svg = readFileSync(path.resolve(here, "../web/public/logo-grid.svg"));
mkdirSync(path.join(here, "build"), { recursive: true });

// High density so the 64px SVG rasterises crisp before downscaling to each icon size.
const render = (size) =>
  sharp(svg, { density: 1200 })
    .resize(size, size, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();

const png1024 = await render(1024);
writeFileSync(path.join(here, "build", "icon.png"), png1024);
console.log("[make-icon] build/icon.png (1024x1024)");

const sizes = [256, 128, 64, 48, 32, 16];
const ico = await pngToIco(await Promise.all(sizes.map(render)));
writeFileSync(path.join(here, "build", "icon.ico"), ico);
console.log(`[make-icon] build/icon.ico (${sizes.join(", ")})`);
